spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: hyeonji2002

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  secret: NiOeyFbN1Gefg9U2XM2jkeIL8XSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI

kakao:
  client_id: e963a78de4d72b6755264d91fb7bb784
  redirect_uri: http://localhost:8080/user/kakao/

cloud:
  aws:
    s3:
      bucket: codyimagebucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAVO7WJPHE3XUYDN3L
      secret-key: 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