spring:

  mail:
    host: smtp.gmail.com
    port: 587
    username: todis.service
    password: johgfzlrxtffmnyd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mvc:
  pathmatch:
    matching-strategy: ant_path_matcher

servlet:
  multipart:
    max-file-size: 50MB
    max-request-size: 50MB

jwt:
  secret: NiOeyFbN1Gefg9U2XM2jkeIL8XSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI

kakao:
  client_id: e963a78de4d72b6755264d91fb7bb784
  redirect_uri: http://ec2-13-209-15-210.ap-northeast-2.compute.amazonaws.com:8080/user/kakao

google:
  client_id: 606786565156-49bmfi8iicjv7cnn1159s247g5redos6.apps.googleusercontent.com
  client_secret: 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
  redirect_uri: http://ec2-13-209-15-210.ap-northeast-2.compute.amazonaws.com:8080/user/google
  token_uri: https://oauth2.googleapis.com/token
  resource_uri: https://www.googleapis.com/oauth2/v2/userinfo

cloud:
  aws:
    s3:
      bucket: codyimagebucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAVO7WJPHE3XUYDN3L
      secret-key: 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